# Generated by Django 4.2.4 on 2023-08-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quizsetting_participants_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsetting',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='quizsetting',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
