# Generated by Django 4.2.4 on 2023-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quizsetting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsetting',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quizsetting',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
