# Generated by Django 4.2.4 on 2023-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_quizsetting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsetting',
            name='participants_limit',
            field=models.IntegerField(null=True),
        ),
    ]
