# Generated by Django 4.2.4 on 2023-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_alter_quizsetting_participants_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('enumeration', 'Enumeration'), ('explanation', 'Explanation'), ('select', 'Select'), ('true-or-false', 'True Or False')], max_length=255),
        ),
    ]
