# Generated by Django 4.2.4 on 2023-08-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_alter_question_answer_alter_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(null=True),
        ),
    ]
